### ISSUE TITLE
[bug] Static minification breaks leaflet marker icon

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/ansible-openwisp2#232] opened 2020-12-04 18:42 UTC
On the current latest master.

How to replicate:

- create a device
- assign a map location to the device

Expected outcome: marker is shown
Actual outcome: marker icon is not found because its name is miscalculated

![Screenshot from 2020-12-04 13-39-11](https://user-images.githubusercontent.com/841044/101201733-34fc0e80-3636-11eb-99ed-04978bd7bb3c.png)

![Screenshot from 2020-12-04 13-42-08](https://user-images.githubusercontent.com/841044/101201952-886e5c80-3636-11eb-8036-7a22fa5864f3.png)

**Comment by nemesisdesign** [comment] 2020-12-04 20:26
I tried switching to `ManifestStaticFilesStorage` but the problem remains.

**Comment by nemesisdesign** [comment] 2020-12-05 02:53
At the moment the only possibility I see is to write a custom `ManifestStaticFilesStorage` class which skips processing these files that give problems. 

Something like this class: https://github.com/TomAnthony/django-flexible-manifest-staticfiles/blob/master/django_flexible_manifest_staticfiles/storages.py, but simpler (eg: just checking `'leaflet' in name`).

So we'll need to construct the final class like this code: https://github.com/armandtvz/django-compress-staticfiles/blob/master/compress_staticfiles/storage.py#L493-L501
But using the extended `ManifestFilesMixin`.

**Comment by pandafy** [comment] 2020-12-06 14:56
After lots of debugging. I found out the reason and solution for this error: https://github.com/Leaflet/Leaflet/pull/7092.  

For the time being, the solution suggested by @nemesisdesign will be the best. It should be added in openwisp-utils in my opinion.

**Comment by nemesisdesign** [comment] 2020-12-07 18:58
> After lots of debugging. I found out the reason and solution for this error: [Leaflet/Leaflet#7092](https://github.com/Leaflet/Leaflet/pull/7092).

Thanks for the analysis Gagan, I also did find that link, but didn't read it entirely, how do you think the two issues are linked?
I have the impression the django manifest file storage class should be able to handle this, unless there's something really unusual in leaflet.

> For the time being, the solution suggested by @nemesisdesign will be the best. It should be added in openwisp-utils in my opinion.

Ok, I had thought we could add it here but adding it to openwisp-utils will be cleaner.

**Comment by pandafy** [comment] 2020-12-08 14:00
> Thanks for the analysis Gagan, I also did find that link, but didn't read it entirely, how do you think the two issues are linked?
I have the impression the django manifest file storage class should be able to handle this, unless there's something really unusual in leaflet.

Leaflet extract location of the icons though [string manipulation using regex](https://github.com/Leaflet/Leaflet/pull/7092/files#diff-65510978f847aaaf9307d30495332de39ecfed44ec25372d1338456e7d953a17L51-R62). Since, they have hard-coded it for the image names that are shipped with the library, the regex breaks for file names containing hash. This patch removes the usage of regex and hence solves the issue. 

Since the issue is created at run-time by JavaScript, it is out of scope of django manifest file storage class functions. 

I suspected this after seeing the names of the file requests were made for. `%22)` rang bells.

![Screenshot from 2020-12-08 19-29-08](https://user-images.githubusercontent.com/32094433/101493212-c3042c00-398b-11eb-83c2-2e895a525c89.png)

**Closed** 2020-12-09 19:08 UTC
Labels: bug, important
