### ISSUE TITLE
Fresh installation on Debian 11.3 completes successfully, but doesn't work

### ISSUE THREAD

**Issue by mattventura** [openwisp/ansible-openwisp2#384] opened 2022-05-14 05:20 UTC
I installed on a fresh VM according to the instructions. The Ansible playbook completed with no errors. 

However, when I navigate to `openwisp.domain.com`, with or without https, with or without the `/admin`, I simply get the nginx '404 Not Found' page.

/opt/openwisp2/log/nginx.access.log and error.log are empty. `systemctl status nginx` doesn't show anything unusual. /etc/nginx/sites-enabled/openwisp *looks* correct to me. Cleared cookies and cache, rebooted the VM, ipv6 on/off, no dice. 
![404](https://user-images.githubusercontent.com/70016/168411879-ac639d14-026b-4043-b079-c5bd1281f302.PNG)

**Comment by nemesisdesign** [comment] 2022-05-15 14:50
The fact that the nginx site path is `/etc/nginx/sites-enabled/openwisp` instead of `/etc/nginx/sites-enabled/openwisp.domain.com` shows that your inventory and playbook may not be configured correctly, see: https://github.com/openwisp/ansible-openwisp2/blob/master/tasks/nginx.yml#L76-L81, the variable `{{ inventory_hostname }}` is used to determine the hostname of the instance, if it's not set correctly (it appears to be just "openwisp" in your case) the application won't work.

I am closing this because it's not a bug report, for more usage questions please use the [support channels](https://openwisp.org/support.html).

**Closed by nemesisdesign** 2022-05-15 14:50 UTC
